ProEfficient.Ui/Controllers/BreakdownEntryEditController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using ProEfficient.Business;
using ProEfficient.Core.CustomAuthorization;
using ProEfficient.Core.Models.ViewModel;
using ProEfficient.Core.Utility;
using ProEfficient.Dal.Utility;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

namespace ProEfficient.Ui.Controllers
{
    [ProEfficientAuthorization]
    public class BreakdownEntryEditController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string apiBaseUrl;

        public BreakdownEntryEditController(IConfiguration configuration)
        {
            _configuration = configuration;
            apiBaseUrl = _configuration.GetValue<string>("ApiUrls");
        }
        // GET: ProductionPage

        public ActionResult Index()
        {
            int OrganizationIDofloginuser = UserUtility.CurrentUser.OrganizationId.ToInteger0();
            int CurrentUserId = UserUtility.CurrentUser.Id;

            var proDate = DateTime.Now.ToString("yyyy-MM-dd");
            var productionBreakDownEntryViewModel = new BreakdownEntryEditPageVM();
            // var productionEntryUI = new ProductionPageVM();           
            productionBreakDownEntryViewModel.UserId = CurrentUserId;
            productionBreakDownEntryViewModel.OrganizationId = OrganizationIDofloginuser;
            //using (var httpClient = new HttpClient())
            //{                
            //    httpClient.BaseAddress = new Uri(apiBaseUrl);
            //    httpClient.DefaultRequestHeaders.Accept.Clear();
            //    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            //    //GET Method  
            //    HttpResponseMessage response = await httpClient.GetAsync("/api/ProductionApi/getProductionEntryUI?ProdDate=" + proDate + "&organizationID=" + OrganizationIDofloginuser);
            //    if (response.IsSuccessStatusCode)
            //    {
            //        string apiResponse = await response.Content.ReadAsStringAsync();
            //        productionEntryUI = JsonConvert.DeserializeObject<ProductionPageVM>(apiResponse);  
            //    }
            //}
            // productionBreakDownEntryViewModel.lstAllShift =productionEntryUI.lstshiftData.ToSelectList(c => c.ShiftId.ToString(), c => c.ShiftName);

            productionBreakDownEntryViewModel.lstAllMachine = UserUtility.AllMachine; //productionEntryUI.lstmachineProductData.ToSelectList(c => c.MachineId.ToString(), c => c.MachineName);
                                                                                      //productionBreakDownEntryViewModel.lstAllStopageReason = productionEntryUI.lststopageData.ToSelectList(c => c.ReasonId.ToString(), c => c.ReasonName);
                                                                                      // productionBreakDownEntryViewModel.lstAllSubStopageReason = productionEntryUI.lststopageData;
            productionBreakDownEntryViewModel.lstBreakdownEntryEditVM = new List<BreakdownEntryEditVM>();
            BreakdownSearchVM breakdownSearchViewModel = new BreakdownSearchVM();
            breakdownSearchViewModel.lstAllShift = UserUtility.AllShift; //productionEntryUI.lstshiftData.ToSelectList(c => c.ShiftId.ToString(), c => c.ShiftName);
            breakdownSearchViewModel.ProductionDate = proDate;
            productionBreakDownEntryViewModel.breakdownSearchVM = breakdownSearchViewModel;
            return View(productionBreakDownEntryViewModel);
        }
        [HttpPost]
        public ActionResult GetBreakdowns(BreakdownSearchVM model)
        {
            var objBreakdown = new BreakDownService(_configuration).DataAccessLayer;
            List<BreakdownEntryEditVM> objBreakdownlst = objBreakdown.GetBreakDownEntryEdit(model.ProductionDate, model.ShiftId).ToList();
            if (objBreakdownlst.Count > 0)
            {
                List<BreakdownEntryEditVM> objBreakdownlstFilter = new List<BreakdownEntryEditVM>();
                decimal.TryParse(_configuration["TotalStoppageTime"], out decimal totalDuration);
                if (totalDuration > 0)
                {
                    foreach (var item in objBreakdownlst)
                    {
                        string[] totalStoppage = item.TotalStoppageTime.Split(':');
                        if (totalStoppage.Length == 3 && Convert.ToDecimal(totalStoppage[0]) * 60 + Convert.ToDecimal(totalStoppage[1]) >= totalDuration)
                        {
                            objBreakdownlstFilter.Add(item);
                        }
                    }

                    ViewBag.ActiveReasons = UserUtility.ActiveReasons;
                    ViewBag.SubStoppageReasons = UserUtility.GetSubstoppagereasonlst();
                }
                return PartialView("_breakdownList", objBreakdownlstFilter);
            }
            else { return Content("No Record Found"); }
        }
        [HttpPost]
        public ActionResult EditBreakdownEntries(IList<BreakdownEntryEditVM> model)
        {
            DataTable UDT = new DataTable();
            UDT.Columns.Add("BreakdownId", typeof(int));
            UDT.Columns.Add("ReasonId", typeof(int));
            UDT.Columns.Add("SubReasonId", typeof(int));
            UDT.Columns.Add("Remarks", typeof(string));
            for (int i = 0; i < model.Count; i++)
            {
                //if (model[i].IsMapped == true)
                //{
                DataRow DR = UDT.NewRow();
                DR["BreakdownId"] = model[i].BreakdownId;
                DR["ReasonId"] = model[i].ReasonId;
                DR["SubReasonId"] = model[i].SubReasonId;
                DR["Remarks"] = model[i].Remarks;
                UDT.Rows.Add(DR);
                // }
            }
            int currentUserId = UserUtility.CurrentUser.Id;
            bool isSaved = new BreakDownService(_configuration).DataAccessLayer.EditBreakDownEntry(UDT);
            List<BreakdownEntryEditVM> li = new List<BreakdownEntryEditVM>();
            if (isSaved)
            {
                return PartialView("_breakdownList", li);
            }
            else { return Content("Error in saving Data. Please contact Administrator"); }
        }


    }
}

ProEfficient.Ui/Views/BreakdownEntryEdit/Index.cshtml
@model ProEfficient.Core.Models.ViewModel.BreakdownEntryEditPageVM
@{

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

   
    <div id="MainContentDiv">
        @{
            var orgids = Model.OrganizationId;
            var allshiftdatalst = Model.lstAllShift;
            var allReasons = Model.lstAllStopageReason;
            var allSubReasons = Model.lstAllSubStopageReason;
        }
        @Html.HiddenFor(i => i.OrganizationId)
        <div class="row">
            <div class="col-md-12">
                <div id="OpPartialBreakdownSearch">
                    <partial name="_breakdownSelect" model="Model.breakdownSearchVM" />
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <div id="OpPartialBreakdownLst">
                    <partial name="_breakdownList" model="Model.lstBreakdownEntryEditVM" />
                </div>
            </div>

        </div>
      
    </div>


   

ProEfficient.Ui/Views/BreakdownEntryEdit/_breakdownList.cshtml
@model IList<ProEfficient.Core.Models.ViewModel.BreakdownEntryEditVM>
@using ProEfficient.Core.Models
@using ProEfficient.Dal.Utility
@using Newtonsoft.Json
@using (Html.BeginForm("EditBreakdownEntries", "BreakdownEntryEdit", FormMethod.Post, new { id = "MappingFrm" }))
{

    <div class="box box-primary">
        <div class="box-header with-border text-center" style="display:none;" id="saveDiv">
            <h3 class="box-title text-center">
                <span id="notificationBadge" style="background-color: red;"
                  class="badge badge-pill badge-danger text-center">You have un-saved changes. Please click "Save to Server".</span>
            </h3>

        </div><!-- /.box-header -->
    <div class="box-body">

            <div style="padding-left:0;padding-right:0;">
                <table id="MappingTable" class="table">
                    <thead>
                        <tr>

                            <th>
                                Machine Name
                            </th>
                            <th>
                                Shift Name
                            </th>
                            <th>
                                Start Time
                            </th>


                            <th>
                                End Time
                            </th>

                            <th>
                                Duration
                            </th>
                            <th>
                                Reason
                            </th>
                            <th>
                                Sub Reason
                            </th>
                            <th>
                                Remarks
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Count > 0)
                        {
                            var activeReasons = (List<SelectListItem>)ViewBag.ActiveReasons;
                            var subStoppageReasons = (List<SubStoppageReason>)ViewBag.SubStoppageReasons;

                            @for (int i = 0; i < Model.Count; i++)
                            {
                                <tr>
                                    @Html.HiddenFor(modelItem => modelItem[i].BreakdownId)
                                    <td>
                                        @Html.DisplayFor(modelItem => modelItem[i].MachineName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => modelItem[i].ShiftName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => modelItem[i].StartTime)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => modelItem[i].EndTime)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => modelItem[i].TotalStoppageTime)
                                    </td>
                                    <td>
                                        @Html.DropDownListFor(modelItem => modelItem[i].ReasonId, activeReasons, "Select Reason", new { @class = "form-control", onchange = "fillsubreasondrp(this)" })

                                    </td>
                                    <td>
                                        @*<select id="subreasonselect" class="form-control"></select>*@
                                        @Html.DropDownListFor(modelItem => modelItem[i].SubReasonId, subStoppageReasons.Where(m => m.ReasonID == Model[i].ReasonId).ToList().ToSelectList(c => c.SubReasonID.ToString(), c => c.SubReasonName), " Select Sub Reason", new { @class = "form-control" })
                                    </td>
                                    <td>
                                        @Html.EditorFor(modelItem => modelItem[i].Remarks)
                                    </td>


                                </tr>
                            }

                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="box-footer">
            <div class="form-group" id="saveDivBtn" style="display:none;">
                <input type="submit" value="Save to Server" class="btn btn-primary pull-right" />
            </div>
        </div>
    </div>
}
<script>
    var substoopageReason =@Html.Raw(JsonConvert.SerializeObject(UserUtility.GetSubstoppagereasonlst()));
    var unsaved = false;
    $(function () {
        $('#MappingTable :input').change(function (e) {
            unsaved = true;
            $('#saveDiv').show();
            $('#saveDivBtn').show();
        });
        var table = $('#MappingTable').DataTable({
            "paging": true,
            "ordering": false,
            "info": false,
            "searching": true,
            "pageLength": 100,
            //"scrollX": true

        });
        // Handle form submission event
        $("#MappingFrm").submit(function (e) {
            debugger;
            // if ($(this).valid()) {
            e.preventDefault();
            // alert($(this).serialize());
            var sData = table.$('select,input').serialize();
            // alert(sData.length);
            if (sData.length > 20) {
                $.ajax({
                    type: "POST",
                    url: $(this).attr('action'),
                    data: sData,
                    success: function (res) {
                        debugger;
                        if (res.length > 0) {
                            unsaved = false;
                            $('#saveDiv').hide();
                            $('#saveDivBtn').hide();
                            $("#OpPartialMachineProductLst").html("");
                            $("#OpPartialMachineProductLst").html(res);
                            alert('Data Saved Successfully ');
                        }
                        else { alert(res); }

                    }
                });
            }
            //}
        });

    });

    function fillsubreasondrp(_this) {

        var reasonid = $(_this).val();
        if (reasonid == "0") {
            alert("Please Select a Valid Reason");
            return;
        }
        var subreasonselect= $(_this).closest("td").next().find("select")
        debugger;
        var datasubreasonbasedonID = substoopageReason.filter(a => a.ReasonID == reasonid);

        var options = "";
        $(subreasonselect).empty();
        options = options + '<option value="0">Select Sub Reason</option>';

        for (var j = 0; j < datasubreasonbasedonID.length; j++) {
            options = options + '<option value=' + datasubreasonbasedonID[j].SubReasonID + '>' + datasubreasonbasedonID[j].SubReasonName + '</option>';
        }

        $(subreasonselect).append(options);

    }
</script>

ProEfficient.Ui/Views/BreakdownEntryEdit/_breakdownSelect.cshtml
@model ProEfficient.Core.Models.ViewModel.BreakdownSearchVM

@using (Html.BeginForm("GetBreakdowns", "BreakdownEntryEdit", FormMethod.Post, new { id = "SearchFrm" }))

{
    @Html.AntiForgeryToken()
    <style>
        .loader {
            top: 0px;
            left: 0;
            position: fixed;
            opacity: 0.8;
            z-index: 10000000;
            background: Black;
            height: 100%;
            width: 100%;
            margin: auto;
        }

        .strip-holder {
            top: 250px;
            -webkit-transform: translateY(-50%);
            -ms-transform: translateY(-50%);
            transform: translateY(-50%);
            left: 50%;
            margin-left: -100px;
            position: relative;
        }
    </style>

    <div class="loader" id="AjaxLoader" style="display:none;">
        <div class="strip-holder">
            <img src="~/Images/loader.gif" alt="Loader" />
        </div>

    </div>
    <div class="row">
        <div class="col-xs-1"></div>
        <div class="col-xs-3">
            <div class="form-group">
                @Html.LabelFor(model => model.ProductionDate, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.ProductionDate, "{0:yyyy-MM-dd}", new { @id = "ProdDate", @class = "form-control newdatepicker", @readonly = true })
                @Html.ValidationMessageFor(model => model.ProductionDate, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="col-xs-1"></div>
        <div class="col-xs-3">
            <div class="form-group">
                @Html.LabelFor(model => model.ShiftId, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(m => m.ShiftId, Model.lstAllShift, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShiftId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-xs-1"></div>
        <div class="col-xs-3">
            <input type="submit" class="btn-primary" value="Get Breakdown List" />
        </div>
        <div id="alert_message" class="alert form-group col-xs-12 col-md-3" style="width:150px;background-color:#f8d7da;display:none">
            <div class="row" style="margin-left:20px"><span><strong>Atention!</strong></span></div>
            <div class="row" style="margin-left:5px"><span>Please select shift</span></div>
        </div>
    </div>
    <link rel="stylesheet" type="text/css" href="~/Scripts/dataTables.bootstrap.min.css" />
    <script type="text/javascript" src="~/Scripts/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/moment.min.js"></script>

    <script>

        $(document).ready(function () {

            $("#SearchFrm").submit(function (e) {

                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    beforeSend: function () {
                        // Show image container
                        $('#AjaxLoader').show();
                    },
                    success: function (res) {

                        if (res.length > 40) {
                            $("#OpPartialBreakdownLst").html("");
                            $("#OpPartialBreakdownLst").html(res);
                        } else {
                            $("#OpPartialBreakdownLst").html("");
                        }
                    }, error: function (err) {
                        $('#AjaxLoader').hide();
                    }
                    ,
                    complete: function (data) {
                        // Hide image container
                        $('#AjaxLoader').hide();
                    }
                });
                // }
            });
        });
    </script>
}