ProEfficient.Ui/Controllers/ProdEfficiencyRDLCController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using OfficeOpenXml;
using ProEfficient.Business;
using ProEfficient.Core.CustomAuthorization;
using ProEfficient.Core.Models;
using ProEfficient.Core.Models.ViewModel;
using ProEfficient.Core.Utility;
using ProEfficient.Dal.DAL;
using ProEfficient.Dal.Utility;
using Rotativa.AspNetCore;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Web.Helpers;

namespace ProEfficient.Ui.Controllers
{
    [ProEfficientAuthorization]
    public class ProdEfficiencyRDLCController : Controller
    {
        private readonly IConfiguration _configuration;

        public ProdEfficiencyRDLCController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        // GET: ProdEfficiency
        public ActionResult Index()
        {

            ProductionReport objVw = new ProductionReport();
            objVw.dtBreakdown = new DataTable();
            objVw.SearchCriteria = Session_ReportSearch;
            return View(objVw);
        }
        [HttpPost]
        public async Task<ActionResult> DisplaySearchResults(ProductionReport criteria, String command)
        {
            //var model = // build list based on the properties of criteria
            ReportDAL rd = new ReportService(_configuration).DataAccessLayer;

            try
            {
                if (command == "Search")
                {
                    #region Search                 
                    string startdate = criteria.StartDate;
                    string enddate = criteria.EndDate;
                    DataSet ds = new DataSet();
                    BreakDownReport bcriteria = new BreakDownReport();

                    DataSet ds1 = new DataSet();
                    try
                    {
                        SearchCriteria ReportSearch = new SearchCriteria();
                        //startdate = startdate.Split('/')[2] + startdate.Split('/')[1] + startdate.Split('/')[0];
                        //enddate = enddate.Split('/')[2] + enddate.Split('/')[1] + enddate.Split('/')[0];
                        ReportSearch.StartDate = startdate;
                        ReportSearch.EndDate = enddate;
                        ReportSearch.MachineID = criteria.MachineID.ToStringWithNullEmpty();
                        ReportSearch.ShiftID = criteria.ShiftId.ToStringWithNullEmpty();

                        startdate = startdate.Split('/')[2] + "-" + startdate.Split('/')[1] + "-" + startdate.Split('/')[0];
                        enddate = enddate.Split('/')[2] + "-" + enddate.Split('/')[1] + "-" + enddate.Split('/')[0];
                        criteria.StartDate = startdate;
                        criteria.EndDate = enddate;


                        Session_ReportSearch = ReportSearch;
                        ds = await rd.GetProductionEffList(criteria);


                        bcriteria.MachineID = criteria.MachineID;
                        bcriteria.StartDate = criteria.StartDate;
                        bcriteria.EndDate = criteria.EndDate;


                        //if (!string.IsNullOrEmpty(ShiftID))
                        //    criteria.ShiftId = Convert.ToInt32(ShiftID);
                        ds1 = await rd.GetBreakDownList(bcriteria);
                    }
                    catch
                    { }
                    DataTable dt = new DataTable();

                    if (ds.Tables.Count > 0)
                        criteria.dtProd = ds.Tables[0];
                    else
                        criteria.dtProd = dt;
                    if (ds1.Tables.Count > 0)
                        criteria.dtBreakdown = ds1.Tables[0];
                    else
                        criteria.dtBreakdown = new DataTable();

                    return View("Index", criteria);

                    #endregion
                }
                else if (command.ToLower() == "ExportExcel".ToLower())
                {
                    #region Export To Excel 
                    string startdate = criteria.StartDate;
                    string enddate = criteria.EndDate;
                    DataSet ds = new DataSet();
                    try
                    {
                        //startdate = startdate.Split('/')[2] + startdate.Split('/')[1] + startdate.Split('/')[0];
                        //enddate = enddate.Split('/')[2] + enddate.Split('/')[1] + enddate.Split('/')[0];
                        startdate = startdate.Split('/')[2] + "-" + startdate.Split('/')[1] + "-" + startdate.Split('/')[0];
                        enddate = enddate.Split('/')[2] + "-" + enddate.Split('/')[1] + "-" + enddate.Split('/')[0];
                        criteria.StartDate = startdate;
                        criteria.EndDate = enddate;
                        ds = await rd.GetProductionEffListExcel(criteria);
                    }
                    catch
                    { }
                    DataTable dt = new DataTable();
                    if (ds.Tables.Count > 0)
                    {

                        var stream = new MemoryStream();

                        using (var package = new ExcelPackage(stream))
                        {
                            var workSheet = package.Workbook.Worksheets.Add("data");
                            workSheet.Cells.LoadFromDataTable(ds.Tables[0], true);
                            package.Save();
                        }
                        stream.Position = 0;
                        string excelName = $"DemoExcel.xlsx";

                        //return File(stream, "application/octet-stream", excelName);  
                        return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);

                        //var gv = new GridView();
                        //gv.DataSource = ds.Tables[0];
                        //gv.DataBind();
                        //Response.ClearContent();
                        //Response.Buffer = true;
                        //Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xls");
                        //Response.ContentType = "application/ms-excel";
                        //Response.Charset = "";
                        //StringWriter objStringWriter = new StringWriter();
                        //HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
                        //gv.RenderControl(objHtmlTextWriter);
                        //Response.Output.Write(objStringWriter.ToString());
                        //Response.Flush();
                        //Response.End();
                        //return View("Index");
                    }
                    else
                    {
                        ProductionReport objVw = new ProductionReport();
                        objVw.dtBreakdown = new System.Data.DataTable();
                        return View(objVw);
                    }
                    #endregion
                }
                else
                {
                    #region Export To PDF
                    string startdate = criteria.StartDate;
                    string enddate = criteria.EndDate;
                    DataSet ds = new DataSet();
                    BreakDownReport bcriteria = new BreakDownReport();

                    DataSet ds1 = new DataSet();
                    try
                    {
                        //startdate = startdate.Split('/')[2] + startdate.Split('/')[1] + startdate.Split('/')[0];
                        //enddate = enddate.Split('/')[2] + enddate.Split('/')[1] + enddate.Split('/')[0];
                        startdate = startdate.Split('/')[2] + "-" + startdate.Split('/')[1] + "-" + startdate.Split('/')[0];
                        enddate = enddate.Split('/')[2] + "-" + enddate.Split('/')[1] + "-" + enddate.Split('/')[0];
                        criteria.StartDate = startdate;
                        criteria.EndDate = enddate;
                        ds = await rd.GetProductionEffList(criteria);


                        bcriteria.MachineID = criteria.MachineID;
                        bcriteria.StartDate = criteria.StartDate;
                        bcriteria.EndDate = criteria.EndDate;
                        bcriteria.MachineID = criteria.MachineID;

                        //if (!string.IsNullOrEmpty(ShiftID))
                        //    criteria.ShiftId = Convert.ToInt32(ShiftID);
                        ds1 = await rd.GetBreakDownList(bcriteria);
                    }
                    catch
                    { }
                    DataTable dt = new DataTable();

                    if (ds.Tables.Count > 0)
                        criteria.dtProd = ds.Tables[0];
                    else
                        criteria.dtProd = dt;
                    if (ds1.Tables.Count > 0)
                        criteria.dtBreakdown = ds1.Tables[0];
                    else
                        criteria.dtBreakdown = new DataTable();

                    return new ViewAsPdf("IndexPdf", criteria);

                    #endregion
                }
            }
            catch (Exception)
            {
                this.CreateObjectAlert("Data not found");
                return View("Index");
            }
        }

        #region chart generation 
        public async Task<ActionResult> CreateColumn(string MachineID, string StartDate, string EndDate, string ShiftID)
        {


            StringBuilder sb = new StringBuilder();
            string startdate = "";
            string enddate = "";
            DataSet ds = new DataSet();
            DataTable dt = new DataTable();
            ReportDAL rd = new ReportService(_configuration).DataAccessLayer;
            try

ProEfficient.Ui/Views/ProdEfficiencyRDLC/Index.cshtml
@using ProEfficient.Dal.Utility
@model ProEfficient.Core.Models.ProductionReport
@{
    ViewBag.Title = "Production Efficiency Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@try
{
    @Html.AntiForgeryToken();
}
catch
{

}
@using (Html.BeginForm("DisplaySearchResults", "ProdEfficiencyRDLC", FormMethod.Post))
{
    <div class="row">
        <div class="col-xs-12">
            <section class="globalForm">
                <h1> Production <span>Efficiency Report</span></h1>
                <hr />
                <div class="form-group col-xs-12 col-md-3">
                    @Html.LabelFor(model => model.MachineID, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(m => m.MachineID, UserUtility.AllMachine, "Select Machine", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MachineID, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-xs-12 col-md-3">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-xs-12 col-md-2">
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-xs-12 col-md-2">
                    @Html.LabelFor(model => model.ShiftId, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(m => m.ShiftId, UserUtility.AllShift, "Select Shift", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ShiftId, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-xs-12 col-md-2">
                    <label class="control-label">&nbsp;</label>
                    <input type="submit" name="command" command="Search" value="Search" class="btn btn-primary" />
                </div>
                @*<div class="form-group col-xs-12 col-md-offset-4 col-md-4">
                    <input type="submit" name="command" command="Search" value="Search" class="btn btn-primary" />
                    <input type="submit" name="command" command="ExportExcel" value="Export To Excel" class="btn btn-primary" />
                    <input type="submit" name="command" command="ExportPdf" formtarget="_blank" value="Export To Pdf" class="btn btn-primary" />
                </div>*@
                <div id="printJS-form" class="printJS-wrapper">
                    @*<div class="form-group col-xs-12 report-table" style="height:250px;overflow:scroll;">
                        @try
                        {
                            @Html.Partial("~/Views/ProdEfficiencyRDLC/ProdReportList.cshtml", Model.dtProd);
                        }
                        catch
                        { }
                    </div>
                    <div class="form-group col-xs-12 report-table">
                        <div class="table-responsive">
                            @try
                            {
                                @Html.Partial("~/Views/BreakDownReport/BreakDownList.cshtml", Model.dtBreakdown)
                            }
                            catch
                            { }
                        </div>
                    </div>*@
                    <div id="dvcharts"> 
                        <div class="form-group col-xs-12 report-table">
                            <div class="table-responsive">
                                <iframe src="about:blank" id="iFrameFinalReport" name="iFrameFinalReport" frameborder="0" width="100%" height="700px;" scrolling="yes"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    @section scripts
{
        <script src="~/Scripts/jquery-easyframe.min.js"></script>
        <script type="text/javascript">
            var StartDate = $("#StartDate").val();
            var EndDate = $("#EndDate").val();
            var MachineID = $("#MachineID").val();
            var ShiftId = $("#ShiftId").val();

            if (MachineID != "") {
                // FOR PRODUCTION PROFILE REPORT
                var columnUrl1 = '/RDLCReports/FinalAllReportResult.aspx?MachineID=' + MachineID + '&StartDate=' + StartDate + '&EndDate=' + EndDate + '&ShiftID=' + ShiftId;
                //GenerateReport(columnUrl, "iFrameProductionProfile");
                //window.frames['iFrameProductionProfileName'].window.location.replace(columnUrl1);

                $('#iFrameFinalReport').easyframe({
                    url: columnUrl1
                }); 
            } 
        </script>
    }
}

ProEfficient.Ui/Views/ProdEfficiencyRDLC/IndexPdf.cshtml
@using ProEfficient.Core.Models.ViewModel
@model ProEfficient.Core.Models.ProductionReport
@{
    ViewBag.Title = "Production Efficiency Report";
    Layout = "~/Views/Shared/_Layoutpdf.cshtml";


    //var Search = (SearchCriteria)Session["SearchCriteria"];
    var Search = Model.SearchCriteria;
}
@try
{
    @Html.AntiForgeryToken();
}
catch
{

}
<div class="form-horizontal">
    <div id="printJS-form">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @try
                {
                    @Html.Partial("~/Views/ProdEfficiency/ProdReportList.cshtml", Model.dtProd);
                }
                catch
                { }
            </div>
            <div class="form-group col-xs-12 report-table">
                @try
                {
                    @Html.Partial("~/Views/BreakDownReport/BreakDownList.cshtml", Model.dtBreakdown)
                }
                catch
                { }
            </div>
        </div>
        <hr />
        <br />
       
            <div id="container" style="width:50%;margin-left:120px;">
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <img src="@Url.Action("CreateLineForLoss","ProdEfficiencyRDLC",new { MachineID=Search.MachineID,StartDate=Search.StartDate,EndDate=Search.EndDate,ShiftID=Search.ShiftID})" alt="column Chart" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <img src="@Url.Action("CreateColumn","ProdEfficiencyRDLC",new { MachineID=Search.MachineID,StartDate=Search.StartDate,EndDate=Search.EndDate,ShiftID=Search.ShiftID})" alt="column Chart" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <img src="@Url.Action("CreatePieForLoss","ProdEfficiencyRDLC",new { MachineID=Search.MachineID,StartDate=Search.StartDate,EndDate=Search.EndDate,ShiftID=Search.ShiftID})" alt="column Chart" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <img src="@Url.Action("CreateColumnLossFrequency","ProdEfficiencyRDLC",new { MachineID=Search.MachineID,StartDate=Search.StartDate,EndDate=Search.EndDate,ShiftID=Search.ShiftID})" alt="column Chart" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <img src="@Url.Action("CreateRadarForLoss","ProdEfficiencyRDLC",new { MachineID=Search.MachineID,StartDate=Search.StartDate,EndDate=Search.EndDate,ShiftID=Search.ShiftID})" alt="column Chart" />
                        </div>
                    </div>
                </div>
            </div> 
    </div>
</div> 

ProEfficient.Ui/Views/ProdEfficiencyRDLC/ProdReportList.cshtml
@model System.Data.DataTable

@{
    ViewBag.Title = "Production Efficency Report";
    
}
<table border="1" cellpadding="5" class="table table-bordered">
    <thead>
        <tr>
            @foreach (System.Data.DataColumn col in Model.Columns)
            {
                <th>@col.Caption</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (System.Data.DataRow row in Model.Rows)
        {
            <tr>
                @foreach (var cell in row.ItemArray)
                {
                <td>@(string.IsNullOrEmpty(cell.ToString())?"0":cell.ToString().Replace(".00",""))</td>
                }
            </tr>
        }
    </tbody>
</table>