ProEfficient.Ui/Controllers/StoppageReasonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using ProEfficient.Business;
using ProEfficient.Core.CustomAuthorization;
using ProEfficient.Core.Models;
using ProEfficient.Dal.Utility;
using System.Linq;

namespace ProEfficient.Ui.Controllers
{
    [ProEfficientAuthorization]
    public class StoppageReasonController : Controller
    {
        private readonly IConfiguration _configuration;

        public StoppageReasonController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public ActionResult Index()
        {

            return View(new StopageReasonService(_configuration).DataAccessLayer.GetStopageReasonList());
        }

        public ActionResult Create()
        {
            LoadStoppageReasonTypeViewBag();
            return View(new StopageReason());
        }

        private void LoadStoppageReasonTypeViewBag()
        {
            var AllStoppageReasonType = new StopageReasonService(_configuration).DataAccessLayer.GetAllStoppageReasonTypes();
            if (AllStoppageReasonType != null)
            {
                ViewBag.AllStoppageReasonType = new SelectList(AllStoppageReasonType, "StoppageReasonTypeID", "StoppageReasonTypeName");
            }
        }
        [HttpPost]
        public ActionResult Create(StopageReason pStopageReason)
        {

            LoadStoppageReasonTypeViewBag();
            if (new StopageReasonService(_configuration).DataAccessLayer.GetStopageReasonList().FirstOrDefault(x => x.ReasonCode.Trim() == pStopageReason.ReasonCode.Trim()) != null)
            {
                ModelState.AddModelError("ReasonCode", "Duplicate Reason Code");
                return View(pStopageReason);
            }
            pStopageReason.IsActive = true;
            pStopageReason.AddBy = UserUtility.CurrentUser.Id;
            pStopageReason.EdittedBy = UserUtility.CurrentUser.Id;
            pStopageReason.OrganizationId = UserUtility.CurrentUser.OrganizationId;
            new StopageReasonService(_configuration).DataAccessLayer.UpdateStopageReason(pStopageReason);
            this.CreateObjectAlert("Stopage Reason");
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            LoadStoppageReasonTypeViewBag();

            var StopageReason = (new StopageReasonService(_configuration).DataAccessLayer.GetStopageReason(new StopageReason() { ReasonId = id }));
            if (StopageReason == null)
            {
                return RedirectToAction("Index");
            }
            return View(StopageReason);
        }


        [HttpPost]
        public ActionResult Edit(StopageReason pStopageReason)
        {
            LoadStoppageReasonTypeViewBag();
            pStopageReason.EdittedBy = UserUtility.CurrentUser.Id;
            new StopageReasonService(_configuration).DataAccessLayer.UpdateStopageReason(pStopageReason);
            this.UpdatedObjectAlert("Stopage Reason");
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {

            var StopageReason = new StopageReasonService(_configuration).DataAccessLayer.GetStopageReason(new StopageReason() { ReasonId = id });
            if (StopageReason != null)
            {
                StopageReason.IsActive = !StopageReason.IsActive;
                StopageReason.EdittedBy = UserUtility.CurrentUser.Id;
                new StopageReasonService(_configuration).DataAccessLayer.UpdateStopageReason(StopageReason);
            }
            return RedirectToAction("Index");
        }
    }
}

ProEfficient.Ui/Views/StoppageReason/Create.cshtml
@model ProEfficient.Core.Models.StopageReason

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var AllStoppageReasonType = (SelectList)ViewBag.AllStoppageReasonType;
    var listOfStoppagereasonType = new SelectList(AllStoppageReasonType.ToList(), "Value", "Text", Model.StoppageReasonTypeId);
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
            <section class="globalForm">
                <h1> Create <span>Stoppage Reason</span></h1>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="form-group col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.ReasonCode, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ReasonCode, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.ReasonCode, "", new { @class = "text-danger" })
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12 col-md-6">
                            @Html.LabelFor(model => model.StoppageReasonTypeId, htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownListFor(model=>model.StoppageReasonTypeId,listOfStoppagereasonType ,"Please select" , new {  @class = "form-control chosen-select" })
                            @Html.ValidationMessageFor(model => model.StoppageReasonTypeId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.ReasonName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ReasonName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.ReasonName, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.IsSchLoss, htmlAttributes: new { @class = "control-label" })
                        @Html.CheckBoxFor(model => model.IsSchLoss, new { @class = "form-check-input", style = "width:20px;height:20px" })
                    </div>
                    <div class="form-group col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.InfluxReasonId, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.InfluxReasonId, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.InfluxReasonId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-xs-12 col-md-4">
                        <i class="fa fa-long-arrow-left" aria-hidden="true"></i> @Html.ActionLink("Back to List", "Index")
                    </div>

                    <div class="form-group col-xs-12 col-md-4 col-md-offset-4">
                        <input type="submit" value="Create" class="btn btn-create-user" />
                    </div>
                </div>
            </section>
        </div>
    </div>
}



@section Scripts {
    <script src="~/js/bundles/jqueryval.min.js"></script>

    @*@Scripts.Render("~/bundles/jqueryval")*@
}

ProEfficient.Ui/Views/StoppageReason/Edit.cshtml
@model ProEfficient.Core.Models.StopageReason

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var AllStoppageReasonType = (SelectList)ViewBag.AllStoppageReasonType;
    var listOfStoppagereasonType = new SelectList(AllStoppageReasonType.ToList(), "Value", "Text", Model.StoppageReasonTypeId);
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
            <section class="globalForm">
                <h1> Edit <span>Stoppage Reason</span></h1>
                <hr />
                @Html.HiddenFor(i => i.AddBy)
                @Html.HiddenFor(i => i.EdittedBy)
                @Html.HiddenFor(i => i.IsActive)
                @Html.HiddenFor(i => i.ReasonId)
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="form-group col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.ReasonCode, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ReasonCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ReasonCode, "", new { @class = "text-danger" })
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12 col-md-6">
                            @Html.LabelFor(model => model.StoppageReasonTypeId, htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownListFor(model=>model.StoppageReasonTypeId,listOfStoppagereasonType ,"Please select" , new {  @class = "form-control chosen-select" })
                            @Html.ValidationMessageFor(model => model.StoppageReasonTypeId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.ReasonName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ReasonName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ReasonName, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.IsSchLoss, htmlAttributes: new { @class = "control-label" })
                        @Html.CheckBoxFor(model => model.IsSchLoss, new { @class = "form-check-label" })
                    </div>
                    <div class="form-group col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.InfluxReasonId, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.InfluxReasonId, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.InfluxReasonId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-xs-12 col-md-4">
                        <i class="fa fa-long-arrow-left" aria-hidden="true"></i> @Html.ActionLink("Back to List", "Index")
                    </div>

                    <div class="form-group col-xs-12 col-md-4 col-md-offset-4">
                        <input type="submit" value="Save" class="btn btn-create-user" />
                    </div>
                </div>
            </section>
        </div>
    </div>
}


@section Scripts {
    <script src="~/js/bundles/jqueryval.min.js"></script>

    @*@Scripts.Render("~/bundles/jqueryval")*@
}

ProEfficient.Ui/Views/StoppageReason/Index.cshtml
@using ProEfficient.Core.Utility
@model IEnumerable<ProEfficient.Core.Models.StopageReason>

@{
    ViewBag.Title = "Reason List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .right15{
        margin-right:15px;
    }
</style>

<h2 class="page-title">Stopage Reason List  @Html.ActionLink("Sub Reason", "Index", "StoppageSubReason", null, new { @class = "btn btn-primary" }) @Html.ActionLink("Create New Reason", "Create", "StoppageReason", null, new { @class = "btn btn-primary right15" })</h2>
<table class="table table-striped table-bordered">
    <thead>
        <tr>       
            <th>
                @Html.DisplayNameFor(model => model.ReasonCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReasonName)
            </th>    
            <th>
                @Html.DisplayNameFor(model => model.IsSchLoss)
            </th>    
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>       
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>       
            <td>
                @Html.DisplayFor(modelItem => item.ReasonCode)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.ReasonName)
            </td>      
            <td>
                @(item.IsSchLoss.ToBoolean() ? "Yes" : "No")
            </td> 
            <td>
                @(item.IsActive.ToBoolean() ? "Active" : "InActive")
            </td>       
            <td class="edit">
                @Html.ActionLink("Edit", "Edit", new { id = item.ReasonId })
            @* @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                @Html.ActionLink(item.IsActive.ToBoolean() ? "Deactivate" : "Activate", "Delete", new {  id=item.ReasonId }, new { @class = "DeleteAnc" })
            </td>
        </tr>
    }
    </tbody>
</table>